data:
  train_file: "data/processed/train.csv"
  test_file: "data/processed/test.csv"

model:
  name: "google/flan-t5-base"
  output_dir: "models/flan_t5_base"

training:
  num_epochs: 3
  batch_size: 4
  warmup_steps: 500
  weight_decay: 0.01
  logging_steps: 100
  save_steps: 500
  eval_steps: 500
  save_total_limit: 2
  input_max_length: 128
  target_max_length: 512

evaluate:
  default_test_input: "Generate ingredients and directions for: Chicken Curry"
  eval_limit: 100  # Number of test samples to evaluate (set lower for faster evaluation)